/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-12-08 06:22:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.Connection;

public final class adminviewPayroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/adminNavbar.jsp", Long.valueOf(1765004106664L));
    _jspx_dependants.put("jar:file:/E:/HMRS%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Human%20Resource%20Management/WEB-INF/lib/jstl-impl.jar!/META-INF/fn.tld", Long.valueOf(1343800018000L));
    _jspx_dependants.put("jar:file:/E:/HMRS%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Human%20Resource%20Management/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343800018000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1765004107804L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Admin Home</title>\n");
      out.write("        <link rel=\"stylesheet\"\n");
      out.write("              href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\n");
      out.write("              integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\n");
      out.write("              crossorigin=\"anonymous\">\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            #nav{\n");
      out.write("                background: #160046;\n");
      out.write("            }\n");
      out.write("            h1{\n");
      out.write("                color: #e7e7e7;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            body {\n");
      out.write("                background-image: url('https://png.pngtree.com/thumb_back/fh260/background/20201101/pngtree-3d-rendering-for-display-product-banner-on-website-image_453005.jpg');\n");
      out.write("                background-repeat: no-repeat;\n");
      out.write("                background-attachment: fixed;\n");
      out.write("                background-size: cover;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #form1>input{\n");
      out.write("                background-color: rgb(239, 0, 0);\n");
      out.write("                color: rgb(255, 255, 255);\n");
      out.write("\n");
      out.write("                font-size: 20px;\n");
      out.write("            }\n");
      out.write("            h1{\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        ");


            response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

            response.setHeader("Pragma", "no-cache");

            response.setHeader("Expires", "0");

            if (session.getAttribute("username") == null) {
                response.sendRedirect("loginadmin.jsp");
            }

        
      out.write("\n");
      out.write("        <header>\n");
      out.write("            <nav id=\"nav\" class=\"navbar navbar-expand-md navbar-dark\">\n");
      out.write("                <div>\n");
      out.write("                    <a class=\"navbar-brand\"> <h1 id=\"h1\" > Human Resource Management System</h1> </a>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <ul class=\"navbar-nav\">\n");
      out.write("                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/emplist\"	class=\"nav-link\">Employee</a></li>\n");
      out.write("                    <li> <a href=\"");
      out.print(request.getContextPath());
      out.write("/leavereq\" class=\"nav-link\">Leaves</a> </li>\n");
      out.write("                    <li> <a href=\"");
      out.print(request.getContextPath());
      out.write("/deptlist\" class=\"nav-link\">Dept list</a> </li>\n");
      out.write("                    <li> <a href=\"");
      out.print(request.getContextPath());
      out.write("/statuslist\" class=\"nav-link\">Projects</a> </li>				\n");
      out.write("                    <li> <a href=\"createANewDepartment.jsp\" class=\"nav-link\">Add Dept</a> </li>\n");
      out.write("                    <li> <a href=\"addEmployeePayroll.jsp\" class=\"nav-link\">Payroll</a> </li>\n");
      out.write("                    <form id=\"form1\" action=\"logout\"><input type=\"submit\"  class=\"nav-link\" value=\"logout\"></form>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <br>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("</html>");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Leave Report List</title>\n");
      out.write("\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            #nav{\n");
      out.write("                background:  #160046;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            #nav>.navbar-brand{\n");
      out.write("                background: white;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            #leave {\n");
      out.write("                font-family: Arial, Helvetica, sans-serif;\n");
      out.write("                border-collapse: collapse;\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #leave td, #customers th {\n");
      out.write("                border: 1px solid #ddd;\n");
      out.write("                padding: 8px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #leave tr:nth-child(even){background-color: #f2f2f2;}\n");
      out.write("\n");
      out.write("            #leave tr:hover {background-color: #ddd;}\n");
      out.write("\n");
      out.write("            #leave th {\n");
      out.write("                padding-top: 12px;\n");
      out.write("                padding-bottom: 12px;\n");
      out.write("                text-align: left;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            #top{\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <h3 id=\"top\">Employees Payroll View</h3>\n");
      out.write("                <hr>\n");
      out.write("                <div class=\"container text-left\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <br>\n");
      out.write("                <table id=\"leave\" class=\"table table-bordered\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th style=\"background-color: #f5d997 ;\">ID</th>\n");
      out.write("                            <th style=\"background-color: yellow;\">Payroll&nbsp;Month</th>\n");
      out.write("                            <th style=\"background-color: yellow;\">Employee Name</th>\n");
      out.write("                            <th style=\"background-color: silver;\">Position</th>                          \n");
      out.write("                            <th style=\"background-color: #ffcf03;width: 18%;\">Basic Salary</th>\n");
      out.write("                            <th style=\"background-color: #008cff;width: 17%;\" >Allowances</th>	\n");
      out.write("                            <th style=\"background-color: #008cff;width: 21%;\" >Deductions</th>\n");
      out.write("                            <th style=\"background-color: Green;color:white;\" >Net Salary</th>\n");
      out.write("                            <th style=\"background-color: red;color:white;\" >Download</th>\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        ");
    try {
                                Class.forName("com.mysql.jdbc.Driver");
                                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chrms", "root", "root");

                                Statement stmt = conn.createStatement();
                                ResultSet rs = stmt.executeQuery("SELECT * FROM payroll_info");

                                while (rs.next()) {
                                    int id = rs.getInt("id");
                        
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>");
      out.print( id);
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(rs.getString("payrollmonth"));
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(rs.getString("employee_name"));
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(rs.getString("position"));
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(rs.getDouble("basic_salary"));
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(rs.getDouble("allowances"));
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(rs.getDouble("deductions"));
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(rs.getDouble("net_salary"));
      out.write("</td>\n");
      out.write("                            <td><a href=\"downloadPDF.jsp?id=");
      out.print(id);
      out.write("\">Download</a></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        ");

                                }

                                conn.close();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        
      out.write("\n");
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
