/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-12-08 06:22:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.itextpdf.kernel.pdf.*;
import com.itextpdf.layout.*;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.property.*;
import com.itextpdf.kernel.colors.*;
import com.itextpdf.layout.borders.*;
import java.io.*;

public final class downloadPDF_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("com.itextpdf.kernel.colors");
    _jspx_imports_packages.add("com.itextpdf.layout.borders");
    _jspx_imports_packages.add("com.itextpdf.kernel.pdf");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.itextpdf.layout");
    _jspx_imports_packages.add("com.itextpdf.layout.element");
    _jspx_imports_packages.add("com.itextpdf.layout.property");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    response.setContentType("application/pdf");
    response.setHeader("Content-Disposition", "attachment; filename=payroll.pdf");

    try (OutputStream outStream = response.getOutputStream()) {
        // Initialize PDF document
        PdfWriter writer = new PdfWriter(outStream);
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document document = new Document(pdfDoc);

        // Add a title to the PDF
        document.add(new Paragraph("Payroll Records")
            .setBold()
            .setFontSize(18)
            .setTextAlignment(com.itextpdf.layout.property.TextAlignment.CENTER));

        // Define table structure
        float[] columnWidths = {50,80, 100, 100, 80, 80, 80, 80}; // Adjust column widths as needed
        Table table = new Table(columnWidths);
        table.setWidth(com.itextpdf.layout.property.UnitValue.createPercentValue(100));

        // Add header cells
        String[] headers = {"ID","Payroll Month", "Employee Name", "Position", "Basic Salary", "Allowances", "Deductions", "Net Salary"};
        for (String header : headers) {
            table.addHeaderCell(new Cell()
                .add(new Paragraph(header).setBold())
                .setBackgroundColor(ColorConstants.LIGHT_GRAY)
                .setTextAlignment(com.itextpdf.layout.property.TextAlignment.CENTER));
        }

        int id =Integer.parseInt(request.getParameter("id"));
        // Fetch data from database
        Class.forName("com.mysql.jdbc.Driver");
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chrms", "root", "root")) {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM payroll_info where id='"+id+"'");

            // Add rows to table
            while (rs.next()) {
                table.addCell(new Cell().add(new Paragraph(String.valueOf(rs.getInt("id")))));
                table.addCell(new Cell().add(new Paragraph(String.valueOf(rs.getString("payrollmonth")))));
                table.addCell(new Cell().add(new Paragraph(rs.getString("employee_name"))));
                table.addCell(new Cell().add(new Paragraph(rs.getString("position"))));
                table.addCell(new Cell().add(new Paragraph(String.format("%.2f", rs.getDouble("basic_salary")))));
                table.addCell(new Cell().add(new Paragraph(String.format("%.2f", rs.getDouble("allowances")))));
                table.addCell(new Cell().add(new Paragraph(String.format("%.2f", rs.getDouble("deductions")))));
                table.addCell(new Cell().add(new Paragraph(String.format("%.2f", rs.getDouble("net_salary")))));
            }
        }

        // Add table to document
        document.add(table);

        // Close the document
        document.close();
    } catch (Exception e) {
        e.printStackTrace();
    }

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
