/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-12-08 05:27:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>CHRMS | Human Resource Management System</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/styles.css\">\n");
      out.write("    <style>\n");
      out.write("        /* Reset */\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            padding-top: 70px; /* space for fixed header */\n");
      out.write("            padding-bottom: 50px; /* space for fixed footer */\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: #eef3f8;\n");
      out.write("            color: #333;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Header */\n");
      out.write("        header {\n");
      out.write("            background: #003366;\n");
      out.write("            padding: 12px 25px;\n");
      out.write("            color: #fff;\n");
      out.write("            box-shadow: 0 1px 4px rgba(0,0,0,0.15);\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            z-index: 1000;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav ul {\n");
      out.write("            list-style: none;\n");
      out.write("            display: flex;\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav li a {\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: white;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: 0.3s;\n");
      out.write("            padding: 6px 10px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav ul li a:hover, nav ul li.active a {\n");
      out.write("            color: #ffcc00;\n");
      out.write("            background: rgba(255,255,255,0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* HERO */\n");
      out.write("        .hero {\n");
      out.write("            background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('images/hr-background.jpg') no-repeat center/cover;\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 110px 20px;\n");
      out.write("            color: white;\n");
      out.write("            border-radius: 0 0 20px 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero h2 {\n");
      out.write("            font-size: 2.8em;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero p {\n");
      out.write("            font-size: 1.3em;\n");
      out.write("            margin-bottom: 25px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn {\n");
      out.write("            background: #ffcc00;\n");
      out.write("            padding: 14px 28px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: #333;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 1.1em;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            transition: 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn:hover { background: #e6b800; }\n");
      out.write("\n");
      out.write("        /* Sections */\n");
      out.write("        section {\n");
      out.write("            width: 85%;\n");
      out.write("            margin: 30px auto;\n");
      out.write("            background: white;\n");
      out.write("            padding: 40px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 0 12px rgba(0,0,0,0.08);\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #services ul {\n");
      out.write("            list-style: none;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #services li {\n");
      out.write("            background: #003366;\n");
      out.write("            color: white;\n");
      out.write("            margin: 12px 0;\n");
      out.write("            padding: 15px;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-size: 1.2em;\n");
      out.write("            transition: 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #services li:hover {\n");
      out.write("            background: #00264d;\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Footer */\n");
      out.write("        footer {\n");
      out.write("            background: #003366;\n");
      out.write("            color: white;\n");
      out.write("            padding: 10px 0;\n");
      out.write("            text-align: center;\n");
      out.write("            position: fixed;\n");
      out.write("            bottom: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            z-index: 1000;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            nav ul { flex-direction: column; gap: 10px; }\n");
      out.write("            .hero h2 { font-size: 2.2em; }\n");
      out.write("            .hero p { font-size: 1.1em; }\n");
      out.write("            section { width: 92%; padding: 30px; }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <header>\n");
      out.write("        <h1>Human Resource Management System</h1>\n");
      out.write("        <nav>\n");
      out.write("            <ul>\n");
      out.write("                <li class=\"active\"><a href=\"home.jsp\">Home</a></li>\n");
      out.write("                <li><a href=\"loginemployee.jsp\">Login</a></li>\n");
      out.write("                <li><a href=\"signup.jsp\">Register</a></li>\n");
      out.write("                <li><a href=\"loginadmin.jsp\">Admin</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <section class=\"hero\">\n");
      out.write("        <h2>Efficient HR Solutions for Your Business</h2>\n");
      out.write("        <p>Manage employees, track attendance, and streamline HR operations.</p>\n");
      out.write("        <a href=\"loginemployee.jsp\" class=\"btn\">Get Started</a>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section id=\"about\">\n");
      out.write("        <h2>About Us</h2>\n");
      out.write("        <p>Our HR management system helps businesses handle employee records, payroll, attendance, and recruitment with ease and automation.</p>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section id=\"services\">\n");
      out.write("        <h2>Our Services</h2>\n");
      out.write("        <ul>\n");
      out.write("            <li>Employee Management</li>\n");
      out.write("            <li>Payroll Processing</li>\n");
      out.write("            <li>Attendance Tracking</li>\n");
      out.write("            <li>Recruitment & Onboarding</li>\n");
      out.write("        </ul>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section id=\"contact\">\n");
      out.write("        <h2>Contact Us</h2>\n");
      out.write("        <p>Email: support@hrm.com | Phone: +123 456 7890</p>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <footer>\n");
      out.write("        <p>&copy; 2025 Human Resource Management. All rights reserved.</p>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
